# -*- coding: utf-8 -*-
"""home.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_4qWJgiJzwrVISxJWl0ISAOLIoomk6H
"""

import streamlit as st

def app():
  #JUDUL HALAMAN APLIKASI
  st.title("Aplikasi Prediksi Batu Ginjal")