# -*- coding: utf-8 -*-
"""visualise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUjtet46Hguq-M81FKvzCOxPP3r8-v5P
"""

import warnings
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import plot_confusion_matrix
from sklearn import tree
import streamlit as st

from web_functions import train_model

def app(df, x, y):

  warnings.filterwarnings('ignore')
  st.set_option('deprecation.showPyplotGlobalUse', False)

  st,title("Visualisasi Prediksi Batu Ginjal")

  if st.checkbox("Plot Confusion Matrix"):
    model, score = train_model(x,y)
    plt.figure(figsize=(10,6))
    plot_confusion_matrix(model,x,y,values_format='d')
    st.pyplot()

  if st.chekbox("Plot Decision Tree")
    model, score = train_model(x,y)
    dot_data = tree.export_graphvis(
        decision_tree=model, max_depth=3, out_file=None,fill=True,rounded=True,feature_names=x.columns, class_names=['nockd','ckd']
    )

    st.graphviz_chart(dot_data)